# Doctor Receptionist AI Agent - System Architecture

## 1. System Overview
An automated WhatsApp receptionist for a clinic. The service collects patient details and symptoms before asking for a requested date, checks clinic schedules and Google Calendar, books a selected slot, restores reminders from MongoDB, and emails a daily Excel report. The Tabler-based dashboard uses authenticated Express endpoints for appointments and doctor settings; browser clients never receive MongoDB credentials.

## 2. Tech Stack Recommendations
- **Language/Framework:** Node.js (Express) or Python (FastAPI)
- **WhatsApp Integration:** Baileys with a clinic-owned QR-linked session
- **Calendar Service:** Google Calendar API (OAuth2)
- **Database:** MongoDB Atlas for conversations, appointments, and expiring operational logs
- **Scheduler/Cron:** Node-Cron for clinic-local daily reports
- **Reports:** ExcelJS workbooks delivered by Nodemailer over TLS
- **Dashboard:** Tabler UI served by Express; authenticated appointment and doctor-settings APIs

## 3. Core Modules & Data Flow
1. **WhatsApp Gateway:** Each doctor initiates Baileys pairing from the dashboard. The one-time QR image is delivered only to that authenticated doctor; session files live in a private OS-local `DoctorBot/sessions/doctor_<doctorId>` directory (or the configured `BAILEYS_AUTH_DIR`) and saved sessions reconnect after restart. Existing `auth_info_baileys/<doctorId>` sessions remain readable for migration compatibility. Incoming text and voice messages are deduplicated and stored per doctor in MongoDB for up to 24 hours, then drained in receipt order with a distributed doctor lease and configurable response delay. Replayed history events are accepted after reconnect.
2. **Conversation Manager:** Loads `doctorName`, `clinicName`, facilities, treatments, consultation details, religion, basic checkup fee, facility rates, and welcome message from the active Doctor profile for every queued message. Facilities, treatments, and their rates are managed in one unified price list on the doctor dashboard (stored once on the Doctor record as `facilityPricing`); greetings and facility answers show current prices with every item listed once. Urdu and English voice notes are converted to WAV and sent to Whisper (translation with transcription fallback) only when `OPENAI_API_KEY` is set and `OPENAI_ALLOW_PHI_PROCESSING=true`; non-retryable voice failures produce an immediate polite ask-to-type reply, while transient provider errors retry through the queue. Gemini receives the same tenant profile for schema-constrained extraction.
3. **Calendar Integration:** Doctors connect through `/api/auth/google` and `/api/auth/google/callback`; OAuth state is signed, short-lived, and one-time. The redirect URI is `GOOGLE_REDIRECT_URI` when configured, otherwise derived from the incoming request, and the identical value is used for the auth request and token exchange; the dashboard displays the exact URI to register in Google Cloud Console to avoid `redirect_uri_mismatch`. Consent requests only the narrow `calendar.freebusy` and `calendar.events` scopes: the full `calendar` scope is a Google RESTRICTED scope and makes Google block sign-in with an OAuth 2.0 policy error until the app completes verification, while these two cover every Calendar call the service makes (free/busy lookup, event insert, event delete). Refresh tokens are encrypted in that doctor's profile. A stored token is never trusted on its own: the callback and `/api/dashboard/calendar/status` call `verifyDoctorCalendarAccess()` against Google and surface the real failure reason (`invalid_grant`, `accessNotConfigured`, missing calendar, timeout), so a broken connection can never be reported as connected. Doctors may retarget a specific calendar ID and disconnect at any time. Requested dates and generated slots must match the doctor's saved working weekdays, manual off-days, and dynamically calculated religion-specific holidays before Google Calendar free/busy is checked. Religious closures are mirrored as all-day Google Calendar events, and doctors (or the superadmin) can override any auto-scheduled holiday from the dashboard to keep the clinic open that day; overrides remove the closure event on the next sync. Booking revalidates the schedule before creating an appointment.
4. **Reminder Queue:** Restores future appointment reminders from MongoDB after WhatsApp reconnects. Offered appointment times are paginated across every open day (`APPOINTMENT_SLOTS_PER_OFFER`, default 12) rather than capped, so afternoon slots stay reachable and a patient can reply "more" for the next page.
5. **Daily Report:** At 00:00 Asia/Karachi, queries each active doctor's booked appointments in the next 24 hours, creates an `.xlsx` attachment with patient details and status, and emails it to that doctor's registered address.
6. **Dashboard:** The PWA at `/dashboard` authenticates database-backed `SUPERADMIN` and `DOCTOR` users with scrypt password hashes and HttpOnly signed sessions. Doctors complete a profile, services, schedule, and off-day setup stored on their Doctor record before WhatsApp pairing is enabled. Doctor APIs scope records by `doctorId`; superadmins can create doctors, view aggregate usage, and suspend accounts.

## 4. Deployment Boundary
The shared Express process is the SaaS control plane. `Doctor` and `DashboardUser` records provide tenant identity and `SUPERADMIN`/`DOCTOR` roles; patient data and dashboard sessions are scoped to `doctorId`. The superadmin can provision doctor accounts (login credentials only — never facilities), supply each doctor's Google OAuth credentials (encrypted with AES-256-GCM), suspend accounts, and view or edit every doctor's full profile, settings, facilities, and pricing at any time through the same unified settings form; partial edits are validated field-by-field and merged, with `setupComplete` recomputed from the merged profile. Each active doctor gets an independent Baileys socket/auth directory and Calendar client; worker synchronization stops sockets for inactive doctors. Baileys device sessions live under `BAILEYS_AUTH_DIR`, which must point at a persistent volume on container platforms because the container filesystem is wiped on every deploy; the dashboard shows a warning while it is unset. The service worker intentionally does not cache dashboard/API responses because they contain PHI. The server migrates legacy unscoped records/indexes to the bootstrap `DOCTOR_ID` at startup, so back up and verify legacy data before deploying this version.

Configure a unique `DOCTOR_ID`, `SUPERADMIN_EMAIL`, a 12+ character `SUPERADMIN_PASSWORD`, 32-byte `DOCTOR_CONFIG_ENCRYPTION_KEY` and `DASHBOARD_SESSION_SECRET`, plus the shared Google OAuth client ID/secret and a `GOOGLE_REDIRECT_URI` registered in Google Cloud Console. Set `WHATSAPP_QUEUE_RESPONSE_DELAY_MS` to tune the inter-reply pause. Voice transcription additionally requires `OPENAI_API_KEY` and explicit patient-data processing approval via `OPENAI_ALLOW_PHI_PROCESSING=true`. The existing `DASHBOARD_EMAIL`/`DASHBOARD_PASSWORD` pair is only used to seed the bootstrap doctor account; dashboard passwords are stored as scrypt hashes. Keep signing/encryption keys, OAuth tokens, message queues, and Baileys auth directories private.

Production must terminate HTTPS at the service or a trusted reverse proxy, use unique secrets, and keep `.env` and Baileys auth files private. Dashboard requests must go through Express; do not expose Atlas connection strings to browser code.